version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
